services:
  frontend:
    image: editor-frontend-dev
    build:
      context: ./Advanced-Clicktrack-Editor-Frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./Advanced-Clicktrack-Editor-Frontend:/usr/src/app
    ports:
      - 3000:3000
    container_name: editor-frontend-dev

  audio-backend:
    image: audio-backend-dev
    build:
      context: ./Advanced-Clicktrack-Audio-Backend
      dockerfile: dev.Dockerfile 
    volumes:
      - ./Advanced-Clicktrack-Audio-Backend:/app
    ports:
      - 5001:5000
    container_name: audio-backend-dev
  
  user-backend:
    image: user-backend-dev
    build:
      context: ./Advanced-Clicktrack-User-Backend
      dockerfile: dev.Dockerfile 
    volumes:
      - ./Advanced-Clicktrack-User-Backend:/usr/src/app
    ports:
      - 3002:3002
    environment:
      NODE_ENV: development
      PORT: 3002
    container_name: user-backend-dev