POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pZ3VlbCIsImlkIjoiNjI2M2ZjNmI1OWJmMzg0MGI4MzZkMTE1IiwiaWF0IjoxNjUwOTczOTk3LCJleHAiOjE2NTA5Nzc1OTd9.ZI5e0FrUlE4bUCcmp4AmKzLQbeNhTagTWAD0nMitm6Y

{
	"title": "Middleware test 3",
	"author": "Billy Jean",
	"url": "https://google.com",
	"likes": 8
}